### ISSUE TITLE
data-gallery attribute doesn't work after upgrade >= 3.0.0

### ISSUE THREAD

**Issue by jschelkens** [biati-digital/glightbox#136]
**Describe the bug**
Before the upgrade, each gallery was grouped according to their data-gallery attribute. After update this is no longer the case (gallery is displayed as one big gallery instead of several different ones according to their data-gallery attribute).

**Are you able to reproduce the bug in the demo site**
No (there are no data-gallery attribute examples on the demo site).
Quick demo here: https://bit.ly/2Z8Zu8x
This creates one big gallery instead of 2 separate galleries (attributes data-gallery="gallery1" &  data-gallery="gallery2")

**Expected behavior**
As was the case before, each gallery is split according to their 'data-gallery' attribute

Thanks

**Comment by Hirbod** [comment]
Any progress on this?

**Comment by biati-digital** [comment]
This error is now fixed in the latest version 3.0.2.

**Comment by Hirbod** [comment]
I can confirm that this Issue has been fixed

**Comment by biati-digital** [comment]
Awesome, closing this issue now

**Comment by Hirbod** [comment]
@biati-digital sorry I was too quick on this. This issue is not fixed. Only the very first gallery on each page works. Every other gallery with another ID I try to open throws now a

`Uncaught TypeError: Cannot read property 'create' of undefined`
<img width="925" alt="Bildschirmfoto 2020-07-28 um 14 49 54" src="https://user-images.githubusercontent.com/504909/88667406-9e489f80-d0e1-11ea-87eb-88c14f992344.png">

**Comment by Hirbod** [comment]
ping @biati-digital

**Comment by biati-digital** [comment]
I'll take a look at that.

**Comment by biati-digital** [comment]
I just published an update that should fix this error, please try it and let me know if it's working for you.

**Comment by smarinade** [comment]
@biati-digital I'm running v3.0.3 and can confirm that the data-gallery attribute is working just fine. Thx
Tested on latest Chrome, Safari and Firefox

**Comment by biati-digital** [comment]
hi @smarinade awesome, thank you for testing the update.

**Comment by Hirbod** [comment]
@biati-digital sorry, I can't confirm it. 3.0.3 is still throwing that error for me

**Comment by biati-digital** [comment]
Hi @Hirbod that's weird, the fix has been confirmed to work by three people including the issue #143

Please verify your code or share a live demo so I can take a look.

**Comment by Hirbod** [comment]
Ok, looks like that issue was on my end, since I am using glightbox inside a horizontal, infinite carousel. I call "destroy" on slideChange now and reinit glightbox, that works now @biati-digital

**Comment by biati-digital** [comment]
Awesome, closing this now.

**Comment by Hirbod** [comment]
@biati-digital ok i was to fast on this again.
The Issu is, that I have a module based app. So I have multiple DOM-markups which initialize GLightbox, which ends up adding n (depends on how many galleries I do have per page) unlimited `<div id="glightbox-body">` body containers for me.

So it looks like I can only initalize gLightbox once per page... 

<img width="670" alt="Bildschirmfoto 2020-08-03 um 03 35 01" src="https://user-images.githubusercontent.com/504909/89138022-6d7dc580-d53a-11ea-906e-1514a885a533.png">

**Comment by Hirbod** [comment]
This also means I can't have multiple skinned galleries per page, which is sad. I would still consider this as a bug. I should be able to initialize as many lightboxes as I need with custom configs.

I might need to use .setElements and parse through the DOM myself instead of using data-gallery

**Comment by biati-digital** [comment]
Actually that's a different issue not related to the galleries bug.

Please open a new issue for the bug you mention.

**Comment by Hirbod** [comment]
Well I think they are kinda related since it wasn't clear to me and IIRC it wasn't a thing in 2.*. I'm in a hurry now, for now I cluttered `window` and injected my last Glighbox instance to it in order to destroy it. Super ugly but my time is running and its a hotfix for now.

**Comment by biati-digital** [comment]
From a code perspective those are different issues not related to each other. I know the code that's why I prefer to keep the issues apart.

Anyway, I'm now aware of this and I'll investigate the issue.
